import './globals.css'

import { Inter } from 'next/font/google'
import Steps from './(components)/Steps/page'
import { Metadata } from 'next';
import Navigator from './(components)/Navigator/page';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({ children }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <head>

            </head>
            <body className=" ">
                <main className=' flex items-center justify-between w-full overflow-hidden h-screen bg-[#b8ff65]'>
                    <div id='ly' className='md:w-[1300px] w-full mdh:h-[90%] md:h-[55%] h-full m-auto border flex justify-between bg-[#f3f3f3] rounded-xl p-1'>
                        <Steps />
                        <div className='w-full h-full relative flex flex-col bg-transparent'>
                            <div className=' overflow-auto w-full h-full flex flex-col'>
                                {children}
                            </div>
                            <Navigator />
                        </div>
                    </div>
                </main>
            </body>
        </html>
    )
}
